export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories/pizza.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories/burger.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 4,
    name: "Chinees",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/categories/cupcake.png"),
  },
];
export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "Soft and fried chicken.",
  restaurants: [
    {
      id: 11,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
      description: "Soft and spicy pizzas.",
      lng: 72.853611,
      lat: 29.1925,
      address: "434 second Street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 12,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 13,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 14,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 15,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 16,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 17,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/dishes/images (2).jpeg"),
      description: "Soft and spicy pizzas.",
      lng: 72.853611,
      lat: 29.1925,
      address: "434 second Street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 18,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 19,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 20,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 21,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 22,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 23,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/dishes/images (2).jpeg"),
      description: "Soft and spicy pizzas.",
      lng: 72.853611,
      lat: 29.1925,
      address: "434 second Street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 24,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 25,
          name: "pizza",
          image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 26,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 27,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 28,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
        {
          id: 29,
          name: "pizza",
          image: require("../assets/images/dishes/images (2).jpeg"),
          price: 10,
          description: "cheezy garlic pizza",
        },
      ],
    },
  ],
};
