export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories/pizza.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories/burger.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 4,
    name: "Chinees",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/categories/cupcake.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/categories/cupcake.png"),
  },
];
export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "Soft and fried chicken.",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
      discription: "Soft and spicy pizzas.",
      lng: 38.149602,
      lat: -85.5424269,
      address: "434 second Street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 11,
          name: "pizza",
          image: require("../assets/images/categories/cupcake.png"),
          price: 10,
          discription: "cheezy garlic pizza",
        },
        {
          id: 12,
          name: "pizza",
          image: require("../assets/images/categories/cupcake.png"),
          price: 10,
          discription: "cheezy garlic pizza",
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
      discription: "Soft and spicy pizzas.",
      lng: 38.149602,
      lat: -85.5424269,
      address: "434 second Street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 13,
          name: "pizza",
          image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
          price: 10,
          discription: "cheezy garlic pizza",
        },
        {
          id: 14,
          name: "pizza",
          image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
          price: 10,
          discription: "cheezy garlic pizza",
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
      discription: "Soft and spicy pizzas.",
      lng: 38.149602,
      lat: -85.5424269,
      address: "434 second Street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 15,
          name: "pizza",
          image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
          price: 10,
          discription: "cheezy garlic pizza",
        },
        {
          id: 16,
          name: "pizza",
          image: require("../assets/images/restaurants/n7yx-hero (1).jpg"),
          price: 10,
          discription: "cheezy garlic pizza",
        },
      ],
    },
  ],
};
